---
_net_filters: &net_filters
  - subnet_name: 10
    network: 10.0.0.0
    network_mask: 255.0.0.0
    description: "all RFC 1918 10/8"
  - subnet_name: 17216
    network: 172.16.0.0
    network_mask: 255.240.0.0
    description: "all RFC 1918 172.16/12"
  - subnet_name: 169254
    network: 169.254.0.0
    network_mask: 255.255.0.0
    description: "all 169.254/16 loopback"
  - subnet_name: 127
    network: 127.0.0.0
    network_mask: 255.0.0.0
    description: "all 127/8 loopback"

udp_session:
  filters: *net_filters
tcp_connect:
  filters: *net_filters
  plugins:
    sourceipmap:
      enabled: True
      hostfiles:
        - '/etc/hosts'
      attribute_key: "source_host"
net_listen:
  snapshot_periodicity: 43200
  protocols: [tcp]
  same_namespace_only: False
  filters:
    - subnet_name: 127
      network: 127.0.0.0
      network_mask: 255.0.0.0
      description: "all 127/8 loopback"
  excludeports:
    - 22222
    - 30000-40000
