ARG     OS_RELEASE
FROM    ubuntu:${OS_RELEASE}

RUN     apt-get update && apt-get -y install \
            python3 \
            python3-pip \
            dh-virtualenv \
            dh-make \
            build-essential \
            debhelper \
            devscripts \
            equivs \
        && apt-get clean

WORKDIR /work
ADD     . /work
ADD     packaging/debian /work/debian

CMD     /work/packaging/debian.sh
